;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AI",DevComment="")
+GameplayTagList=(Tag="AI.Checks",DevComment="")
+GameplayTagList=(Tag="AI.Checks.IsMeleeWeaponEquipped",DevComment="")
+GameplayTagList=(Tag="AI.Checks.IsRangedWeaponEquipped",DevComment="")
+GameplayTagList=(Tag="Char",DevComment="")
+GameplayTagList=(Tag="Char.Actions",DevComment="")
+GameplayTagList=(Tag="Char.Actions.Aiming",DevComment="")
+GameplayTagList=(Tag="Char.Actions.Attacking",DevComment="")
+GameplayTagList=(Tag="Char.Actions.Blocking",DevComment="")
+GameplayTagList=(Tag="Char.Actions.ChangingWeapons",DevComment="")
+GameplayTagList=(Tag="Char.Actions.Dodging",DevComment="")
+GameplayTagList=(Tag="Char.Actions.Drink",DevComment="")
+GameplayTagList=(Tag="Char.Actions.Jumping",DevComment="")
+GameplayTagList=(Tag="Char.Actions.MagicBlock",DevComment="")
+GameplayTagList=(Tag="Char.Actions.Rest",DevComment="")
+GameplayTagList=(Tag="Char.Actions.Swiming",DevComment="")
+GameplayTagList=(Tag="Char.Checks",DevComment="")
+GameplayTagList=(Tag="Char.Checks.CanFireArrow",DevComment="")
+GameplayTagList=(Tag="Char.Checks.ClimbingLadder",DevComment="")
+GameplayTagList=(Tag="Char.Checks.ControlRotation",DevComment="")
+GameplayTagList=(Tag="Char.Checks.HasActuallyFiredBow",DevComment="")
+GameplayTagList=(Tag="Char.Checks.HoldingRMB",DevComment="")
+GameplayTagList=(Tag="Char.Checks.IsChainLighting",DevComment="")
+GameplayTagList=(Tag="Char.Checks.isDead",DevComment="")
+GameplayTagList=(Tag="Char.Checks.IsEvading",DevComment="")
+GameplayTagList=(Tag="Char.Checks.isExecutingAbility",DevComment="")
+GameplayTagList=(Tag="Char.Checks.isPlayer",DevComment="")
+GameplayTagList=(Tag="Char.Checks.isRainingArrows",DevComment="")
+GameplayTagList=(Tag="Char.Checks.Strafing",DevComment="")
+GameplayTagList=(Tag="Char.Checks.Targeting",DevComment="")
+GameplayTagList=(Tag="Char.Checks.WeaponEquipped",DevComment="")
+GameplayTagList=(Tag="Char.State",DevComment="")
+GameplayTagList=(Tag="Char.State.Indominable",DevComment="")
+GameplayTagList=(Tag="Char.State.Invulnerability",DevComment="")
+GameplayTagList=(Tag="Char.State.Parring",DevComment="")
+GameplayTagList=(Tag="Char.State.Stun",DevComment="")

